version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:1.0
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - app-network
  kafka:
    image: debezium/kafka:1.0
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - app-network
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      - MSSQL_SA_PASSWORD=1q2w3e4r@#
      - ACCEPT_EULA=Y
    networks:
      - app-network
  connect:
    image: debezium/connect:1.0
    ports:
      - 8083:8083
    links:
      - kafka
      - sqlserver
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    networks:
      - app-network
networks:
  app-network:
    driver: bridge